workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 30
    instance_type: mac_mini_m1 # Ou linux si dispo, c'est le standard
    environment:
      groups:
        - sdk_config
      vars:
        PACKAGE_NAME: "io.groam.aura" # À vérifier dans ton AndroidManifest
      java: 17
    scripts:
      - name: Set permissions
        script: chmod +x gradlew
      - name: Build Android APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - TON_EMAIL@exemple.com # Mets ton mail ici pour recevoir l'APK
