workflows:
  native-android:
    name: Build AURA APK
    max_build_duration: 120
    instance_type: mac_mini_m2 # Machine de build standard
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "io.groam.aura" # Remplace par ton vrai package name si besoin
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - TON_EMAIL@gmail.com # Mets ton adresse ici pour recevoir l'APK
